<form action="" method="post">
	<table class="table">
		<tr>
			<td>Icon: </td>
			<td>
				<select name="ICON_TRANGTHAI" style="width:200px">
					<option value="moi">Mới</option>
					<option value="km">Khuyến mãi</option>
					<option value="hot">Hot</option>
					<option value="">Không Có</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>Trạng Thái: </td>
			<td>
				<select name="TEN_TRANGTHAI" style="width:200px">
					<option value="0">Còn hàng</option>
					<option value="1">Sắp hết hàng</option>
					<option value="2">Sắp ra mắt</option>
					<option value="3">Đang sả hàng</option>
					<option value="4">Hết hàng</option>
					<option value="5">Không kinh doanh</option>
					<option value="6">Bán chạy</option>
				</select>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="submit" class="btn btn-primary" value="Lưu lại" />
				<input type="button" onclick="window.location.reload()" class="btn btn-default" value="Nhập lại" />
			</td>
		</tr>
	</table>
	
	<input type="hidden" name="action" value="7" />
	<input type="hidden" name="id" value="<?php echo $_GET["id"] ?>" />
	<input type="hidden" name="ngaycapnhat" value="<?php date_default_timezone_set('Asia/Ho_Chi_Minh'); $now=getdate(); echo $now["year"].'/'.$now["mon"].'/'.$now["mday"].' '.$now["hours"].':'.$now["minutes"].':'.$now["seconds"] ?>" />
</form>
<script type="text/javascript">
	$(document).ready(function(){
		var trangthai="<?php echo $this->data['icon']; ?>";

		$("select[name='ICON_TRANGTHAI']").val(trangthai);
		

		var tentrangthai="<?php echo $this->data['trangthai']; ?>";

		$("select[name='TEN_TRANGTHAI']").val(tentrangthai);
		
	});
</script>