<section class="layout_center">
	<div id="iconeventleft"></div>
	<div id="iconeventright"></div>

	<nav id="breadcrumb-global">
		<ul class="clearfix">
			<li><a href="/">Trang chủ</a><span style="margin-left:5px;">»</span></li><li><h1>Giới thiệu</h1></li>
		</ul>
	</nav>
	<div class="clearleft"></div>
		
	<p>Đồ án thiết kế website bán hàng bằng zend framework và mô hình MVC.</p>
	<p>Giáo viên hướng dẫn: Từ Minh Mẫn</p>
	<p>Thực hiện</p>
		<div class="sidebar">
    		<div class="sidebar-rotater">
    		<table style="margin: 0 auto;">
    		<tr>
    		<td>
        		<table>
		        	<form action="">
		        		<tr><td>Họ tên:</td><td><input type="text" value="Trần Công Tuấn"></td></tr>
		        		<tr><td>Lớp:</td><td><input type="text" value="12CTH1"></td></tr>
		        		<tr><td>MSSV:</td><td><input type="text" value="1200378"></td></tr>
		        	</form>
        		</table>
        	</td>
        	<td>	
        		<table>
		        	<form action="">
		        		<tr><td>Họ tên:</td><td><input type="text" value="Trần Văn Thỏa"></td></tr>
		        		<tr><td>Lớp:</td><td><input type="text" value="12CTH1"></td></tr>
		        		<tr><td>MSSV:</td><td><input type="text" value="1202063"></td></tr>
		        	</form>
        		</table>
        	</td>
        	</tr>	
        	</table>
    		</div>
		</div>

</section>
<style>
	p{
		font-size:14px;
		text-align:center;
	}
	.sidebar {
    perspective: 800px;
    text-align:center;
   	
}

.sidebar-rotater {
    transform: rotateY(-25deg);
    transition: transform 1s;
}
 
.sidebar-rotater:hover {
    transform: rotateY(0deg);
}

</style>