<form method="POST" id="frmnganluong" action="https://www.nganluong.vn/button_payment.php">
    <input type="hidden" name="receiver" value="tranvanthoa2@gmail.com" />
    <input type="hidden" name="product_name" value="<?php echo $this->hoadontt ?>" />
    <input type="hidden" name="price" value="<?php echo $this->sum; ?>" />
    <input type="hidden" name="comments" value="Mua hàng tại vienthonga" />
    <input type="hidden" name="return_url" value="<?php echo $_SERVER["HTTP_HOST"].$this->baseUrl() ?>/gio-hang?autosubmit=true">
</form>

<script type="text/javascript">
window.onload=function(){
	document.getElementById("frmnganluong").submit();
}
</script>