<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/Scripts/nicEdit.js"></script>
<script type="text/javascript">
	$(".breadcrumb").html("<li><i class='fa fa-dashboard'></i> <a href='"+base_url+"/admin'>Trang Chủ</a></li> <li><i class='fa fa-life-saver'></i><a href='"+base_url+"/admin/website'> Website</a></li> <li class='active'><i class='fa fa-lock'></i> Bảo Trì</li>");
	$("h1.page-header").text("Bảo Trì Website");
$(function(){
		
	$("#qlwebsite").parent().addClass("active").find("a").click();
	$("#qlwebsite").find("li:eq(7)").addClass("active");
	});
</script>

<?php $this->headTitle("Bảo Trì Website - Admin Control Panel"); ?>

<form method="post" action="">
	<input type="hidden" name="l" value="<?php echo ($this->baotri=='0')?'1':'0'; ?>" />
	<input type="submit" class="btn btn-default" value="<?php if($this->baotri=="0") echo 'Bảo trì website'; else echo 'Kết thúc bảo trì website' ?>" />
</form>