<script type="text/javascript">
	$(".breadcrumb").html("<li><i class='fa fa-dashboard'></i> <a href='"+base_url+"/admin'>Trang Chủ</a></li> <li><i class='fa fa-life-saver'></i><a href='"+base_url+"/admin/website'> Website</a></li> <li class='active'><i class='fa fa-css3'></i> Css</li>");
	$("h1.page-header").text("Cập Nhật Css");
$(function(){
		
	$("#qlwebsite").parent().addClass("active").find("a").click();
	$("#qlwebsite").find("li:eq(3)").addClass("active");
	});
</script>
<?php 
        $this->headTitle("Chỉnh Sửa Css"); 
        $fh = fopen('public/Contents/css.css',"r");
		$text="";
		while ($line = fgets($fh)) {
		  $text.=$line;
		}
		fclose($fh);
?>
<form method="post" action="" enctype="multipart/form-data">
	<input type="file" name="hinhanh" />
	<br />
	<input type="submit" class="btn-default btn" value="Tải Lên Hình Ảnh" />
	<input type="hidden" name="l" value="1" />
</form>
<br /><br />
<?php if($this->filename!=null) echo $this->filename.'<br /><br />'; ?>
<form method="post" action="">
	<textarea name="event" class="input" style="width:98%" rows="20"><?php echo $text ?></textarea><br /><br />
	<input type="submit" class="btn btn-primary" value="Lưu Lại" />
	<input type="hidden" name="l" value="2" />
</form>