<link href="<?php echo $this->baseUrl() ?>/public/admin/inputstyle.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/Scripts/validate.js"></script>
<script type="text/javascript">
	$(function(){
		$("#frm1").kiemtra([
			{
				'name':'email',
				'email':true
			},
			{
				'name':'password',
				'trong':true
			},
			{
				'name':'repassword',
				'sosanhdoituong':true,
				'name2':'password',
				'message':'Nhap lai mat khau sai'
			},
			{
				'name':'name',
				'string':true
			},
			{
				'name':'address',
				'trong':true
			},
			{
				'name':'phone',
				'sodt':true
			},
			{
				'name':'s_name',
				'string':true
			},
			{
				'name':'s_address',
				'trong':true
			},
			{
				'name':'captcha',
				'trong':true
			}
		]);
		$("#elm_ship_to_another").change(function(){
			if(!$(this).is(":checked")){
				$("#sa .input-text").removeClass("disabled").removeAttr('disabled');
			}else{
				$("#sa .input-text").addClass("disabled").attr('disabled','disabled');
			}
		});
	});
</script>
<section class="layout_center">
	<div id="iconeventleft"></div>
	<div id="iconeventright"></div>
	<nav id="breadcrumb-global">
		<ul class="clearfix">
			<li><a href="/">Trang chủ</a><span style="margin-left:5px;">»</span></li><li><h1>Đăng ký</h1></li>
		</ul>
	</nav>
	<div class="clearleft"></div>
	<div class="contentboxdk">
		<?php if($this->message!=null){ ?>
		<div class="red" style="width:380px;text-align:center;font-weight:bold">
			<?php echo $this->message ?>
		</div>
	<?php } ?>
		<form name="profile_form" action="" method="post" id="frm1">
						
		<div class="border">
			<div class="subheaders-group">		
			<h2 class="subheader">
			
			THÔNG TIN TÀI KHOẢN
			</h2>
		<div class="form-field">
			<label for="email" class="cm-required cm-email cm-trim">Email :</label>
			<input type="email" id="email" name="email" size="32" maxlength="128" value="<?php if(isset($_POST['email'])) echo $_POST['email']; ?>" class="input-text"> <span id="email1"></span>
		</div>
			
		<div class="form-field">
			<label for="password1" class="cm-required cm-password">Mật khẩu:</label>
			<input type="password" id="password1" name="password" size="32" maxlength="32" value="" class="input-text cm-autocomplete-off" autocomplete="off">
			<span id="password11"></span>
		</div>

		<div class="form-field">
			<label for="password2" class="cm-required cm-password">Xác nhận mật khẩu:</label>
			<input type="password" id="password2" name="repassword" size="32" maxlength="32" value="" class="input-text cm-autocomplete-off" autocomplete="off">
		</div>

			<h2 class="subheader">
			
			SINH NHẬT

			</h2>
		<div class="form-field">
			<label for="birthday">Ngày sinh</label>
			
				<select name="ngaysinh">
					<option value="0">Ngày</option>
					<?php 
						for($i=1;$i<=31;$i++)
							echo "<option value='".$i."'>".$i."</option>";
					 ?>
				</select>
				<select name="thangsinh">
					<option value="0">Tháng</option>
					<?php 
						for($i=1;$i<=12;$i++)
							echo "<option value='".$i."'>".$i."</option>";
					 ?>
				</select>
				<select name="namsinh">
					<option  value="0">Năm</option>
					<?php 
						for($i=1970;$i<=2040;$i++)
							echo "<option value='".$i."'>".$i."</option>";
					 ?>
				</select>

		</div>		


			<h2 class="subheader">
			
			THÔNG TIN LIÊN HỆ

			</h2>
				
					

		<div class="form-field">
			<label for="elm_36" class="cm-profile-field  ">CMND:</label>
			  		<input type="text" id="elm_36" name="cmnd" size="32" value="<?php if(isset($_POST['cmnd'])) echo $_POST['cmnd']; ?>" class="input-text ">
			</div>



										
																															
					


			<h2 class="subheader">
			
			ĐỊA CHỈ THANH TOÁN

			</h2>
				
					       

							
		<div class="form-field">
			<label for="elm_14" class="cm-profile-field cm-required ">Họ Tên:</label>
			  		<input type="text" id="elm_14" name="name" size="32" value="<?php if(isset($_POST['name'])) echo $_POST['name']; ?>" class="input-text ">
			</div>
					       

							
		<div class="form-field">
			<label for="elm_18" class="cm-profile-field cm-required ">Địa chỉ:</label>
			  		<input type="text" id="elm_18" name="address" size="32" value="<?php if(isset($_POST['address'])) echo $_POST['address']; ?>" class="input-text ">
			</div>
					       

							
					       

							
		<div class="form-field">
			<label for="elm_30" class="cm-profile-field cm-required cm-phone ">Điện thoại liên lạc:</label>
			  		<input type="text" id="elm_30" name="phone" size="32" value="<?php if(isset($_POST['phone'])) echo $_POST['phone']; ?>" class="input-text ">
			</div>


					

			
			<h2 class="subheader">
				<span class="title-extra" style="padding-right:20px">
					
					<label><input class="checkbox" id="elm_ship_to_another" type="checkbox" name="copy" checked="checked"> Địa chỉ thanh toán giống địa chỉ nhận hàng </label>
				</span>
			
				ĐỊA CHỈ NHẬN HÀNG

			</h2>
			<div id="sa">
				
					       

							
		<div class="form-field">
			<label for="elm_15" class="cm-profile-field cm-required ">Họ Tên:</label>
			  		<input type="text" id="elm_15" name="s_name" size="32" value="" class="input-text disabled" disabled="disabled">
			</div>
					       

							
		<div class="form-field">
			<label for="elm_19" class="cm-profile-field cm-required ">Địa chỉ :</label>
			  		<input type="text" id="elm_19" name="s_address" size="32" value="" class="input-text disabled" disabled="disabled">
			</div>
					       

	
					       

							
		<div class="form-field">
			<label for="elm_31" class="cm-profile-field  cm-phone ">Điện thoại liên lạc:</label>
			  		<input type="text" id="elm_31" name="s_phone" size="32" value="" class="input-text disabled" disabled="disabled">
			</div>

		</div>

				
				<h2 class="subheader">
			
			XÁC NHẬN

			</h2>
				
					

		<div class="form-field">
			<label for="elm_40" class="cm-profile-field  ">Mã Xác Nhận:</label>
				<div class="left">
			  		<input type="text" id="elm_40" name="captcha" size="20" value="" class="input-text" style="width:115px">
			  	</div>
			  	<div class="left" style="margin-left:5px">
			  		<img src="<?php echo $this->baseUrl() ?>/captcha" id="imgcaptcha" />
			  	</div>
			  	<div class="clearleft"></div>
			</div>
			
				
				</div>
		</div>
				<div class="buttons-container" style="margin-left:165px">
												
			
		 
			<input type="submit" value="Đăng ký">

							</div>
			</form>
			<?php if(isset($_POST['s_name'])){ ?>
			<script type="text/javascript">
			$(function(){
					$("#elm_ship_to_another").prop('checked', false).change();
			})
			
			</script>
			<?php } ?>
			
		</div>
</section>