<section class="layout_center">

	<div id="iconeventleft"></div>
	<div id="iconeventright"></div>
	<?php 
		$url="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
		$url=explode("?", $url)[0];
		$url.="?";
		if($_GET["sort"]!=null){
			$url.="sort=".$_GET["sort"]."&";
		}
		if($_GET["page"]!=null){
			$url.="page=".$_GET["page"]."&";
		}
		 ?>

	<div class="left" style="width:200px;padding:5px;margin-top:5px">
	<?php if($this->hangsx!=null){ ?>
		<div class="sidebox">
	        <h3>XEM THEO HÃNG</h3>
	        <div class="content contentl boxhang">
	            <?php foreach ($this->hangsx as $item) {
	            	echo "<a href='".($this->baseUrl()."/".$item["URL"]).".html'>".$item["TEN_LOAI"]."</a>";
	            } ?>
	        </div>
	    </div>
	<?php } ?>
		<div class="sidebox">
	        <h3>TÌM KIẾM THEO GIÁ</h3>
	        <div class="content contentl">
	        	<a href="<?php echo substr($url,0,strlen($url)-1) ?>">Tất Cả Giá</a>
	            <a href="<?php echo $url."bgia=0&egia=1000000" ?>">Nhỏ Hơn 1 Triệu</a>
	            <a href="<?php echo $url."bgia=1000000&egia=5000000" ?>">1 Triệu - 5 Triệu</a>
	            <a href="<?php echo $url."bgia=6000000&egia=10000000" ?>">6 triệu - 10 triệu</a>
	            <a href="<?php echo $url."bgia=10000000" ?>">Trên 10 triệu</a>
	        </div>
	    </div>

	    <div class="sidebox">
	        <h3>TINH TRẠNG</h3>
	        <div class="content contentl">
	        	<a href="<?php echo substr($url,0,strlen($url)-1) ?>">Tất Cả Sản Phẩm</a>
	            <a href="<?php echo $url."gg=1" ?>">Sản Phẩm Giảm Giá</a>
	            <a href="<?php echo $url."km=1" ?>">Sản Phẩm Khuyến Mãi</a>
	            <a href="<?php echo $url."rm=1" ?>">Sản Phẩm Sắp Ra Mắt</a>
	        </div>
	    </div>

	</div>
	<div class="left" style="width:975px">
		<nav id="breadcrumb-global">
			<ul class="clearfix">
				<li><a href="/">Trang chủ</a><span style="margin-left:5px;">»</span></li>
				<?php echo $this->nav; ?>
			</ul>
		</nav>
		<div class="clearleft"></div>
		<div class="boxproduct boxproductbig">
				<div class="headerbox">
					<h3 class="left"><?php echo $this->info["TEN_LOAI"] ?></h3>
					<h3 class="right">
						<form method="get" action="" id="frmsort">
							<select name="sort">
								<option value="1">Mới nhất</option>
								<option value="2">Cũ nhất</option>
								<option value="3">Giá tăng dần</option>
								<option value="4">Giá giảm dần</option>
							</select>	
						</form>
					</h3>
					<div class="clear"></div>
				</div>
				<div class="contentbox">
						
						<?php 
							if(count($this->sp)>0){foreach ($this->sp as $isp) {
						 ?>
						<div class="item">
							<a href="<?php echo $this->baseUrl().'/'.$isp['URL'].'_'.$isp['MASP'] ?>.html" class="noneunder">
								<div class="beforhover">
									<i class="iconstatus <?php echo $isp["ICON_TRANGTHAI"] ?>"></i>
									<div class="product-image">
										<img width="150" height="120" src="<?php echo $this->baseUrl().'/uploads/images/sp/'.$isp["HINHANH"] ?>" />
									</div>
									<div class="product-info">
										<div class="product-name"><?php echo $isp["TENSP"] ?></div>
										<div class="product-price">
											<?php
											if($isp["GIA"]>0){
												if($isp["GIAM_GIA"]==0)
										            echo  number_format($isp["GIA"],0,',','.')." VND";
										        else{
										        	echo number_format(((100-$isp["GIAM_GIA"])*$isp["GIA"])/100,0,',','.')." VND"; 
										        }
									    	}
									        else{
									        	echo "Liên Hệ";
									        }
											?>
										</div>
									</div>
								</div>
								<div class="afterhover">
									<div class="product-info">
										<div class="product-name"><?php echo $isp["TENSP"] ?></div>
										<div class="product-price">
											<?php if($isp["GIA"]>0){echo "Giá gốc: ".number_format($isp["GIA"],0,',','.')." VND";} else{echo "Liên Hệ";} ?>
										</div>
									</div>
									<div class="product-s">
										<?php echo $isp["TOM_TAT_TS"] ?>
									</div>
									<div class="promo-info"><span class="icon icon-product-promo"></span><?php if($isp["GIAM_GIA"]==0){ ?>Khuyến mãi
										<?php }else{ ?>
										Giảm Giá <?php echo $isp["GIAM_GIA"] ?>%
										<?php } ?>
									</div>		
									<div class="product-o">
										<?php if($isp["GIA"]>0){ ?>
											<a class="btn-buy btn-a left" href="<?php echo $this->baseUrl().'/gio-hang?id='.$isp["MASP"] ?>">
												<i class="icon left"></i>
												ĐẶT HÀNG
											</a>
										<?php } ?>
										<a href="<?php echo $this->baseUrl().'/yeu-thich?id='.$isp["MASP"] ?>" title="Thêm vào yêu thích" class="icon icon-like left"></a>
										<div class="clearleft"></div>
									</div>
								</div>
							</a>
						</div>
						<?php }}else echo "Chưa có sản phẩm."; ?>
						
						<div class="clear"></div>
				</div>
			</div>
			<div class="right" style="margin-right: 35px;">
				<?php echo $this->partial('admin/phan_trang.phtml',array('arr_page'=>$this->arr_page)); ?>
				
			</div>
			<div class="clear"></div>
	</div>
	<div class="clearleft"></div>
</section>
<script type="text/javascript">
	$(function(){
		$("#frmsort select").change(function(){
			$(this).parent().submit();
		});
		var sort="<?php echo (isset($_GET['sort']))?$_GET['sort']:1; ?>";
		$("#frmsort select").val(sort);
	});
</script>
<link href="<?php echo $this->baseUrl() ?>/public/admin/page.css" rel="stylesheet" type="text/css" />
<style type="text/css">
	nav#breadcrumb-global{
		margin-left: 0px !important;
		margin-top: 5px;
	}
</style>