<script type="text/javascript">
	$(function(){
		$("h1.page-header").text("Lỗi Truy Cập Trang");
		$(".breadcrumb").html("<li><i class='fa fa-dashboard'></i> <a href='"+base_url+"/admin'>Trang Chủ</a></li> <li class='active'><i class='fa fa-info-circle'></i> Thông Báo</li>");
	});
</script>
<div class="row">
   
                    <div class="col-lg-12">
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <i class="fa fa-info-circle"></i> Bạn Không Có Quyền Vào Trang Này.
                        </div>
                    </div>
                </div>
