 <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/Scripts/dialog.js"></script>
 <link href="<?php echo $this->baseUrl() ?>/public/Contents/dialog.css" rel="stylesheet" />
<script type="text/javascript">

 var dialogxoa=null;
 var frmxoa=null; 

	$(function(){
		$(".breadcrumb").html("<li><i class='fa fa-dashboard'></i> <a href='"+base_url+"/admin'>Trang Chủ</a></li> <li class='active'><i class='fa fa-male'></i> Danh Sách Nhân Viên</li>");
	$("h1.page-header").text("Danh Sách Nhân Viên");
	$("#qlnhanvien").parent().addClass("active").find("a").click();
	$("#qlnhanvien").find("li:eq(0)").addClass("active");
	});

		$(function(){
			$(".table select").change(function(){
				LoadJson(base_url+"/ajax/changenhomnv",{"id":$(this).attr("data-id"),"group":$(this).val()},function(result){

				});
			});

			dialogxoa=new dialog($("#dialog"),{
            "width":500,
            "height":240
        });
        dialogxoa.init();

        $(".frmxoatt").submit(function(){
      if(!$(this).hasClass("success")){
        frmxoa=$(this);
        dialogxoa.show();
        return false;
      }
    });

		});

function xoatt(th){
    

    LoadJson(base_url+"/ajax/kiemtraxoa",{"mk2":th.find(".mk2").val(),"ma":th.find(".ma").val()},function(result){
            switch(result){
                case 0:
                    $("#dialog .ms").html('Mật khẩu cấp 2 sai.').css("color","red");
                    break;
                case 2:
                    $("#dialog .ms").html('Mã bảo vệ sai').css("color","red");
                    $("#dialog img").attr("src",base_url+"/captcha");
                    break;
                case 1:
                    frmxoa.addClass("success").submit();
                    break;
            }
        });
        
        return false;

}

</script>
<style type="text/css">
	.opa{
		opacity: 0.5;
	}
	.disable{
		background-color: #ccc;
	}
</style>
<?php if($this->quyen["THEMNV"]==1){ ?>
<a href="<?php echo $this->baseUrl() ?>/admin/themnhanvien" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Thêm nhân viên mới</a>
<?php } ?>


<div id="dialog">
    <div class='header'>
        XÁC NHẬN XÓA NHÂN VIÊN
    </div>
    <div class='ct'>
        <p>Vui lòng nhập mật khẩu cấp 2 để tiếp tục xóa.</p>
        <div class='ms' style="margin-top:-10px;text-align:center"></div>
            <br />
        <form action="" method="post" role="form" onsubmit="return xoatt($(this));">
            <div class='row'>
                <div class='col-lg-4 col-sm-4 col-xs-4' style="margin-top:7px"><b>Mật Khẩu Cấp 2:</b> </div>
                <div class='col-lg-6 col-sm-6 col-xs-6'>
                    <input type="password" class="form-control mk2" />
                </div>
            </div>
            <br />
            <div class='row'>
                <div class='col-lg-4 col-sm-4 col-xs-4' style="margin-top:7px"><b>Mã Xác Nhận:</b> </div>
                <div class='col-lg-8 col-sm-8 col-xs-8'>
                    <input size="18" type="text" class="ma" />
                    <img src="<?php echo $this->baseUrl() ?>/captcha" style="padding-left:7px" />
                </div>
            </div>
            <br />
            <div class='row'>
                <div class='col-lg-4 col-sm-4 col-xs-4' style="margin-top:7px"></div>
                <div class='col-lg-6 col-sm-6 col-xs-6'>
                    <input type="submit" class="btn btn-success btn-sm" value="Tiếp tục xóa" />
                    <input type="button" onclick="dialogxoa.hide();" class="btn btn-default btn-sm" value="Hủy bỏ" />
                </div>
            </div>
        </form>
    </div>
</div>


<?php if($this->message!=null){ ?>
	<div class="message">
		<?php echo $this->message ?>
	</div>
<?php } ?>
<br /><br />
	<div class="clearfix">
		<div class="l">
			<?php echo $this->partial('admin/phan_trang.phtml',array('arr_page'=>$this->arr_page)); ?>
		</div>
		<div class="r">
			<div class="l">
				<form method="get" action="">
					<div class="frmsearch clearfix">
						<input type="text" class="textboxsearch" value="<?php if(isset($_GET['q'])) echo $_GET['q']; ?>"  placeholder="Nhập tên hoặc tk nv..." name="q" />
						<input type="submit" class="buttonsearch" value="" />
					</div>
					<?php if(isset($_GET["sort"])){ ?>
						<input type="hidden" name="sort" value="<?php echo $_GET["sort"] ?>" />
					<?php } ?>
				</form>
			</div>
			<div class="l" style="margin-left:10px">
				<form method="get" action="">
					<select onchange="$(this).parent().submit();" name="sort" style="height:25px">
						<option value="manv-desc">Mới Thêm</option>
						<option value="manhom">Nhóm</option>
						<option value="khoa">Trạng Thái</option>
						<option value="gioitinh">Giới tính</option>
					</select>
					<?php if(isset($_GET["q"])){ ?>
						<input type="hidden" name="q" value="<?php echo $_GET["q"] ?>" />
					<?php } ?>
				</form>
			</div>
		</div>
	</div>
<div class="table-responsive">
<table class="table table-bordered table-vm">
	<tr>
		<th>Họ Tên</th>
		<th>GT</th>
		<th>ĐT</th>
		<th>Email</th>
		<th>Tài Khoản</th>
		<th>MK</th>
		<th>MK cấp 2</th>
		<th>Nhóm</th>
		<th>Trang Thái</th>
		<th></th>
		<th></th>
	</tr>
	<?php foreach ($this->data as $item) {
		?>
		<tr>
			<td>
				<?php echo $item["HOTEN"] ?>
			</td>
			<td align="center">
				<?php echo ($item["GIOITINH"]==0)?"Nữ":"Nam"; ?>
			</td>
			<td>
				<?php echo $item["DIENTHOAI"] ?>
			</td>
			<td>
				<?php echo $item["EMAIL"] ?>
			</td>
			<td>
				<?php echo $item["TAIKHOAN"] ?>
			</td>
			<td align="center">
				<?php if($this->quyen["SUANV"]==1){ ?>
				<form method="post" action="" onsubmit="return confirm('Bạn có chắc muốn reset lại mật khẩu cho nhân viên này?. Mật khẩu sẽ được đặt lại là 123456');">
						<input type="<?php if($this->iduser!=$item['MANV']) echo 'submit'; else echo 'button' ?>" title="Reset Mật Khẩu" value="" style="background-image:url(<?php echo $this->baseUrl() ?>/public/admin/Images/refresh.png);width:15px;height:15px;border:0;cursor:pointer;<?php if($this->iduser==$item['MANV']) echo 'opacity:0.5;' ?>" />
						<input type="hidden" name="id" value="<?php echo $item["MANV"] ?>" />
						<input type="hidden" name="action" value="resetmk" />
						<input type="hidden" name="name" value="<?php echo $item["HOTEN"] ?>" />
					</form>
					<?php } ?>
			</td>
			<td align="center">
				<?php if($this->quyen["SUANV"]==1){ ?>
				<form method="post" action="" onsubmit="return confirm('Bạn có chắc muốn reset lại mật khẩu cấp 2 cho nhân viên này?. Mật khẩu sẽ được đặt lại là 123456');">
						<input type="<?php if($this->iduser!=$item['MANV']) echo 'submit'; else echo 'button' ?>" title="Reset Mật Khẩu" value="" style="background-image:url(<?php echo $this->baseUrl() ?>/public/admin/Images/refresh.png);width:15px;height:15px;border:0;cursor:pointer;<?php if($this->iduser==$item['MANV']) echo 'opacity:0.5;' ?>" />
						<input type="hidden" name="id" value="<?php echo $item["MANV"] ?>" />
						<input type="hidden" name="action" value="resetmk2" />
						<input type="hidden" name="name" value="<?php echo $item["HOTEN"] ?>" />
					</form>
					<?php } ?>
			</td>
			<td align="center" width="110px">
				<select style="width:100px" data-id="<?php echo $item["MANV"] ?>" <?php if($this->iduser==$item['MANV']) echo "disabled='disabled' class='disable'"; ?> >
				<?php foreach ($this->nhom as $i) {
					if($i["MANHOM"]!=$item["MANHOM"])
						echo '<option value="'.$i["MANHOM"].'">'.$i["TENNHOM"].'</option>';
					else
						echo '<option value="'.$i["MANHOM"].'" selected="selected">'.$i["TENNHOM"].'</option>';
				} ?>
				</select>
			</td>
			<td align="center">
			<?php if($this->quyen["KHOANV"]==1){ ?>
				<form method="post" action="" onsubmit="return confirm('Bạn có chắc?');">
				<input <?php if($this->iduser==$item['MANV']) echo "class='opa'"; ?> type='<?php if($this->iduser!=$item['MANV']) echo 'submit'; else echo 'button' ?>'
				<?php if($item["KHOA"]==1){ echo "value='Đang khóa' style='background:transparent url(".$this->baseUrl()."/public/admin/Images/lock.png) no-repeat left center;padding-left:20px;border:0;cursor:pointer'";}else{echo "value='Đang hoạt động' style='background:transparent url(".$this->baseUrl()."/public/admin/Images/unlock.png) no-repeat left center;padding-left:20px;border:0;cursor:pointer'";} ?> />
				<input type="hidden" name="action" value="trangthai" />
				<input type="hidden" name="trangthai" value="<?php echo $item["KHOA"] ?>" />
				<input type="hidden" name="manv" value="<?php echo $item["MANV"] ?>" />
				</form>
				<?php } ?>
			</td>
			<td align="center">
			<?php if($this->quyen["SUANV"]==1){ ?>
				<a title="Chỉnh Sửa" href="<?php echo $this->baseUrl() ?>/admin/suanv?id=<?php echo $item["MANV"] ?>"><img src="<?php echo $this->baseUrl() ?>/public/admin/Images/edit.png" /></a>
			<?php } ?>
			</td>
			<td align="center">
			<?php if($this->quyen["KHOANV"]==1 && $this->iduser!=$item["MANV"]){ ?>
				<form method="post" action="" class="frmxoatt">
						<input type="submit" title="Xóa nhân viên" value="" style="background-image:url(<?php echo $this->baseUrl() ?>/public/admin/Images/delete.png);width:15px;height:15px;border:0;cursor:pointer;" />
						<input type="hidden" name="id" value="<?php echo $item["MANV"] ?>" />
						<input type="hidden" name="action" value="removenv" />
						<input type="hidden" name="name" value="<?php echo $item["HOTEN"] ?>" />
					</form>
			<?php } ?>
			</td>
		</tr>
	<?php } ?>
</table>

<script type="text/javascript">
		var sort="<?php if(isset($_GET['sort'])) echo $_GET['sort']; else echo 'manv-desc' ?>";

		if(sort!="manv-desc"){
			$("select[name='sort']").val(sort);
		}
</script>
<?php if($this->quyen["SUANV"]==0){ ?>
<script type="text/javascript">
	$(function(){
		$(".table td select").attr("disabled","disabled").css("background-color","#ccc");
	});
</script>
	<?php } ?>