<script type="text/javascript">
		$(".breadcrumb").html("<li><i class='fa fa-dashboard'></i> <a href='"+base_url+"/admin'>Trang Chủ</a></li> <li><i class='fa fa-star'></i><a href='"+base_url+"/admin/nhom'> Nhóm</a></li> <li><i class='fa fa-edit'></i> Sửa Nhóm</li> <li class='active'><i class='fa fa-bookmark'></i> <?php echo $this->data["TENNHOM"] ?></li>");
	$("h1.page-header").text("Cập Nhật Nhóm "+"<?php echo $this->data["TENNHOM"] ?>");
$(function(){
		
	$("#qlnhom").parent().addClass("active").find("a").click();
	});
$(function(){
$("form").kiemtra([
		{
			'name':'TENNHOM',
			'trong':true
		}
	]);
});
	
</script>
<?php if($this->message!=null){ ?>
	<div class="message">
		<?php echo $this->message ?>
	</div>
<?php } ?>
<form method="post" action="">
	<table class="table">
		<tr>
			<td><b>Tên Nhóm: </b><span class="red">*</span></td>
			<td>
				<textarea name="TENNHOM" style="width:100%"><?php echo $this->data["TENNHOM"] ?></textarea>
			</td>
		</tr>
		<tr class="bordertop">
			<td><b>Phân Quyền: </b><span class="red">*</span></td>
			<td>
				<table class="table">
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">SẢN PHẨM</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSSP']) echo 'checked="checked"'; ?> name="XEMDSSP-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSSP']) echo 'disabled="disabled"'; ?> name="XEMDSSP-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Thêm: </td>
						<td><input type="checkbox" <?php if($this->data['THEMSP']) echo 'checked="checked"'; ?> name="THEMSP-boolean" value="1" /><input type="hidden" <?php if($this->data['THEMSP']) echo 'disabled="disabled"'; ?> name="THEMSP-boolean" value="0" /></td>
					</tr>
					<tr>
						<td width="30%">Sửa: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['SUASP']) echo 'checked="checked"'; ?> name="SUASP-boolean" value="1" /><input type="hidden" <?php if($this->data['SUASP']) echo 'disabled="disabled"'; ?> name="SUASP-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Xóa: </td>
						<td><input type="checkbox" <?php if($this->data['XOASP']) echo 'checked="checked"'; ?> name="XOASP-boolean" value="1" /><input type="hidden" <?php if($this->data['XOASP']) echo 'disabled="disabled"'; ?> name="XOASP-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">TIN TỨC</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSTT']) echo 'checked="checked"'; ?> name="XEMDSTT-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSTT']) echo 'disabled="disabled"'; ?> name="XEMDSTT-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Thêm: </td>
						<td><input type="checkbox" <?php if($this->data['THEMTT']) echo 'checked="checked"'; ?> name="THEMTT-boolean" value="1" /><input type="hidden" <?php if($this->data['THEMTT']) echo 'disabled="disabled"'; ?> name="THEMTT-boolean" value="0" /></td>
					</tr>
					<tr>
						<td width="30%">Xóa: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XOATT']) echo 'checked="checked"'; ?> name="XOATT-boolean" value="1" /><input type="hidden" <?php if($this->data['XOATT']) echo 'disabled="disabled"'; ?> name="XOATT-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Sửa: </td>
						<td><input type="checkbox" <?php if($this->data['SUATT']) echo 'checked="checked"'; ?> name="SUATT-boolean" value="1" /><input type="hidden" <?php if($this->data['SUATT']) echo 'disabled="disabled"'; ?> name="SUATT-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">NHÂN VIÊN</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSNV']) echo 'checked="checked"'; ?> name="XEMDSNV-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSNV']) echo 'disabled="disabled"'; ?> name="XEMDSNV-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Thêm: </td>
						<td><input type="checkbox" <?php if($this->data['THEMNV']) echo 'checked="checked"'; ?> name="THEMNV-boolean" value="1" /><input type="hidden" <?php if($this->data['THEMNV']) echo 'disabled="disabled"'; ?> name="THEMNV-boolean" value="0" /></td>
					</tr>
					<tr>
						<td width="30%">Sửa: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['SUANV']) echo 'checked="checked"'; ?> name="SUANV-boolean" value="1" /><input type="hidden" <?php if($this->data['SUANV']) echo 'disabled="disabled"'; ?> name="SUANV-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Xóa / Khóa: </td>
						<td><input type="checkbox" <?php if($this->data['KHOANV']) echo 'checked="checked"'; ?> name="KHOANV-boolean" value="1" /><input type="hidden" <?php if($this->data['KHOANV']) echo 'disabled="disabled"'; ?> name="KHOANV-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">ĐƠN HÀNG</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSDH']) echo 'checked="checked"'; ?> name="XEMDSDH-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSDH']) echo 'disabled="disabled"'; ?> name="XEMDSDH-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Xóa: </td>
						<td><input type="checkbox" <?php if($this->data['XOADH']) echo 'checked="checked"'; ?> name="XOADH-boolean" value="1" /><input type="hidden" <?php if($this->data['XOADH']) echo 'disabled="disabled"'; ?> name="XOADH-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">NHÓM</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSN']) echo 'checked="checked"'; ?> name="XEMDSN-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSN']) echo 'disabled="disabled"'; ?> name="XEMDSN-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Thêm: </td>
						<td><input type="checkbox" <?php if($this->data['THEMNHOM']) echo 'checked="checked"'; ?> name="THEMNHOM-boolean" value="1" /><input type="hidden" <?php if($this->data['THEMNHOM']) echo 'disabled="disabled"'; ?> name="THEMNHOM-boolean" value="0" /></td>
					</tr>
					<tr>
						<td width="30%">Xóa: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XOANHOM']) echo 'checked="checked"'; ?> name="XOANHOM-boolean" value="1" /><input type="hidden" <?php if($this->data['XOANHOM']) echo 'disabled="disabled"'; ?> name="XOANHOM-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Sửa: </td>
						<td><input type="checkbox" <?php if($this->data['SUANHOM']) echo 'checked="checked"'; ?> name="SUANHOM-boolean" value="1" /><input type="hidden" <?php if($this->data['SUANHOM']) echo 'disabled="disabled"'; ?> name="SUANHOM-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">KHÁCH HÀNG</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSKH']) echo 'checked="checked"'; ?> name="XEMDSKH-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSKH']) echo 'disabled="disabled"'; ?> name="XEMDSKH-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Xóa / Khóa: </td>
						<td><input type="checkbox" <?php if($this->data['KHOAKH']) echo 'checked="checked"'; ?> name="KHOAKH-boolean" value="1" /><input type="hidden" <?php if($this->data['KHOAKH']) echo 'disabled="disabled"'; ?> name="KHOAKH-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">LOẠI SẢN PHẨM</td>
					</tr>
					<tr>
						<td width="30%">Xem Danh Sách: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XEMDSLSP']) echo 'checked="checked"'; ?> name="XEMDSLSP-boolean" value="1" /><input type="hidden" <?php if($this->data['XEMDSLSP']) echo 'disabled="disabled"'; ?> name="XEMDSLSP-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Thêm: </td>
						<td><input type="checkbox" <?php if($this->data['THEMLSP']) echo 'checked="checked"'; ?> name="THEMLSP-boolean" value="1" /><input type="hidden" <?php if($this->data['THEMLSP']) echo 'disabled="disabled"'; ?> name="THEMLSP-boolean" value="0" /></td>
					</tr>
					<tr>
						<td width="30%">Xóa: </td>
						<td width="5%"><input type="checkbox" <?php if($this->data['XOALSP']) echo 'checked="checked"'; ?> name="XOALSP-boolean" value="1" /><input type="hidden" <?php if($this->data['XOALSP']) echo 'disabled="disabled"'; ?> name="XOALSP-boolean" value="0" /></td>
						<td width="30%" class="borderleft">Sửa: </td>
						<td><input type="checkbox" <?php if($this->data['SUALSP']) echo 'checked="checked"'; ?> name="SUALSP-boolean" value="1" /><input type="hidden" <?php if($this->data['SUALSP']) echo 'disabled="disabled"'; ?> name="SUALSP-boolean" value="0" /></td>
					</tr>
					<tr style="font-weight: bold;border-bottom: 1px solid #ccc;margin-top: 10px;">
						<td colspan="4">NHẬN XÉT</td>
					</tr>
					<tr>
						<td width="15%">Xem Danh Sách: </td>
						<td width="20%"><input type="checkbox" <?php if($this->data['XEMDSNX']) echo 'checked="checked"'; ?> name="XEMDSNX-boolean" value="1" /><input type="hidden" name="XEMDSNX-boolean" value="0" <?php if($this->data['XEMDSNX']) echo 'disabled="disabled"'; ?> /></td>
						<td width="15%" class="borderleft">Xóa: </td>
						<td><input <?php if($this->data['XOANX']) echo 'checked="checked"'; ?> type="checkbox" name="XOANX-boolean" value="1" /><input type="hidden" name="XOANX-boolean" value="0"  <?php if($this->data['XOANX']) echo 'disabled="disabled"'; ?> /></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
				<td>

				</td>
				<td colspan="3">
					<input type="submit" class="btn-primary btn" value="Cập Nhật" />
					<input type="reset" class="btn btn-default" value="Nhập lại" />
				</td>
			</tr>
	</table>
</form>
<script type="text/javascript">
	$(function(){
			$("input:checkbox").change(function(){
				if(this.checked){
					$(this).parent().find("input").eq(1).attr("disabled","disabled");
				}else{
					$(this).parent().find("input").eq(1).removeAttr("disabled");
				}
			});
	});
</script>